"""
Given two strings s and t which consist of only lowercase letters.
String t is generated by random shuffling string s and then add one more letter at a random position.
Find the letter that was added in t.

Input:
s = "abcd"
t = "abcde"
Output:
e
Explanation:
'e' is the letter that was added.
"""
from collections import Counter
def findTheDifference(s,t):
    if len(s) == 0:
        return t
    s_count = Counter(s)
    t_count = Counter(t)
    for key in t_count.keys():
        if not key in s_count or t_count[key] - s_count[key] > 0:
            return key

#using XOR operation
def findDifference(s,t):
    res = 0
    for letter in s:
        res ^= ord(letter)
    for letter in t:
        res ^= ord(letter)
    return chr(res)
s = "abcd"
t = "acdbu"
#print(findTheDifference(s,t))
print(findDifference(s,t))
